HTTP/1.1 401 Unauthorized
x-frame-options: SAMEORIGIN
x-xss-protection: 0
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
content-type: application/json; charset=utf-8
cache-control: no-cache
x-request-id: 5356dd22-1030-4f2d-b056-e7fcfd299c53
x-runtime: 0.069102
content-length: 32

{"error":"Invalid access_token"}exit_code=0
