import os,pathlib,json,subprocess
root=pathlib.Path.cwd();tmp=root/'tmp/r09';prefix='final-required';e=os.environ.copy();e['GIT_INDEX_FILE']=str(tmp/(prefix+'.index'))
def git(*a):return subprocess.check_output(['git',*a],env=e).decode().strip()
git('read-tree','HEAD');git('add','-A','--','.');source=git('write-tree');git('update-ref','refs/r09/offer-final-required-source-20260912',source,'0'*40)
(tmp/(prefix+'-identity.json')).write_text(json.dumps({'source_tree':source},indent=2)+'\n')
paths=json.loads((tmp/'required-r09-rails-paths.json').read_text());assert len(paths)==len(set(paths));assert all((root/p).exists() for p in paths)
changed=git('diff','--name-only','9a834e756347822d4ae5af15f268a5e8751fc852',source).splitlines();specs=[p for p in changed if p.startswith('spec/') and p.endswith('_spec.rb') and (root/p).exists()];assert not set(specs)-set(paths)
(tmp/(prefix+'-inventory.json')).write_text(json.dumps({'source_tree':source,'required_rails_files':paths,'changed_existing_rails_spec_files':specs,'missing_changed_specs':sorted(set(specs)-set(paths))},indent=2)+'\n')
s=(tmp/'verify_ui_required.py').read_text().replace('ui-required',prefix).replace('import os,subprocess,pathlib,json,sys','import os,subprocess,pathlib,json,sys,datetime')
s=s.replace("[('vue',vue),('rails',ruby)","[('rails',ruby),('vue',vue)")
s=s.replace("with (root/f'tmp/r09/final-required-{name}.log')", "started=datetime.datetime.now(datetime.timezone.utc).isoformat()\n print(json.dumps({'starting':name,'at':started,'source_tree':source}),flush=True)\n with (root/f'tmp/r09/final-required-{name}.log')")
s=s.replace("run={'name':name", "run={'started_at':started,'finished_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'name':name")
s=s.replace("if result.returncode and name!='rubocop':", "if result.returncode:")
(tmp/'verify_final_required.py').write_text(s)
print(json.dumps({'source_tree':source,'rails_files':len(paths),'changed_rails_specs':len(specs)}))
